---
title: "Proteins"
output: html_document
date: "2025-07-22"
---

## **Load BiomaRt**

-   Used hsapiens gene dataset

```{r}
library("biomaRt")

listMarts()
ensembl <- useMart("ENSEMBL_MART_ENSEMBL")

ensembl_datasets <- listDatasets(ensembl)
head(ensembl_datasets)

ensembl <- useDataset("hsapiens_gene_ensembl", mart= ensembl)

filters = listFilters(ensembl)
write.table(filters, "filters.tsv", sep = '\t', row.names =
FALSE, quote = FALSE)

attributes = listAttributes(ensembl)
write.table(attributes, "attributes.tsv", sep = '\t', row.names
= FALSE, quote = FALSE)

# Which attributes are sequences
seqs_attributes <- attributes[which(attributes$page == 'sequences'),]

```

### Define attributes and filters, getBM

```{r}


attributes01 <- c(
     "ensembl_gene_id",
     "gene_biotype",
     'description',
     "coding",
     "peptide")

filters01 <- c("chromosome_name", "biotype")

values01 <- list(chromosome_name=1, biotype='protein_coding')



```

## Look though all chromosome protein coding values

```{r}
# All chromosomeses, meaning repeat 4 times with different chromosomes

values02 <- list(chromosome_name=c('1', '2','3', '4', '5' ), biotype='protein_coding')

info02 <- getBM(
     attributes=attributes01,
     filters=filters01,
     values=values02,
     mart=ensembl)


```

### Filter output

```{r}

# Drop sequence unavailable

info01 <- info01[which(info01$coding != 'Sequence unavailable'),]

colnames(info01) <-c('descriprion', 'peptide', 'coding', 'peptide', 'ensembl_gene_id')


# For some reason there are empty values on this attribute
info01$peptide <- NULL

info_copy <- info01


```

## Add the type of protein corresponds to the value

```{r}

# 

library(stringr)

# Classify into membrane, nuclear(Have similar number of outputs)
membrane <- info_copy[str_detect(info_copy$descriprion, 'membrane'),]
nuclear <- info_copy[str_detect(info_copy$descriprion, 'nuclear'),]



nuclear$type <- 'nuclear'
membrane$type <- 'membrane'

data <- rbind(kinase, nuclear, membrane)

data_copy <- data

data_copy$description <- NULL# AND SO ON until there is only coding and type
data_copy$ensembl_gene_id <- NULL
data_copy$gene_biotype <- NULL



write.csv(data_copy, file='C:/Users/theos/Desktop/internship/protein_data.csv')

```
